import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Next Construction Website",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
         <head>
         <link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet"></link> 
         <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
         </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}